# Generated by Django 4.2.16 on 2024-12-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
